# Generated by Django 3.1.5 on 2021-01-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zipcode',
            name='areaCode',
            field=models.TextField(max_length=5, verbose_name='zipcode'),
        ),
    ]
